# Generated by Django 5.2.3 on 2025-06-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='fristname',
            new_name='firstname',
        ),
    ]
